service: lottery-shop

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - '.*/**'
    - '*'
    - apps/**
    - coverage/**
    - layers/**
    - libs/**
    - node_modules/**
    - src/**
    - test/**

functions:
  index:
    handler: dist/lambda.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any
